spring.application.name=bakery-manager

# JPA Common

# Format entity attribute match with the column in database
# Example: fullName -> full_name
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Default profile
spring.profiles.active=dev
